# Generated by Django 3.2.19 on 2023-08-08 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20230808_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='week_of_month',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
