# Generated by Django 3.2.19 on 2023-08-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincompany',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
