# Generated by Django 3.2.19 on 2023-08-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20230812_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfeedback',
            name='date_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskfeedback',
            name='date_in_dev_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskfeedback',
            name='date_processing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskfeedback',
            name='date_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskfeedback',
            name='date_testing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskfeedback',
            name='date_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
