# Generated by Django 3.2.19 on 2023-08-14 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20230814_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.TextField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.sprint')),
            ],
        ),
        migrations.AddField(
            model_name='taskfeedback',
            name='sprints',
            field=models.ManyToManyField(related_name='tasks_sprints', to='todo.Sprint'),
        ),
    ]
