# Generated by Django 3.2.19 on 2023-08-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20230814_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
