# Generated by Django 3.2.19 on 2023-08-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_meeting_meeting_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='employee',
            field=models.ManyToManyField(related_name='meetings', to='todo.Employee'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='members',
            field=models.ManyToManyField(related_name='meetings', to='todo.Member'),
        ),
    ]
