# Generated by Django 3.2.19 on 2023-08-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_auto_20230814_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='employee',
            field=models.ManyToManyField(related_name='sprints', to='todo.Employee'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='members',
            field=models.ManyToManyField(related_name='sprint', to='todo.Member'),
        ),
    ]
