# Generated by Django 3.2.19 on 2023-08-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_auto_20230814_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='members',
        ),
    ]
