# Generated by Django 3.2.19 on 2023-08-17 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_auto_20230814_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.task'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.sprint'),
        ),
    ]
