# Generated by Django 3.2.19 on 2023-08-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_auto_20230817_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapitem',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
