# Generated by Django 3.2.19 on 2023-08-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_roadmapitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskduration',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskduration',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
