# Generated by Django 3.2.19 on 2023-08-23 16:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0024_alter_duration_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
