# Generated by Django 3.2.19 on 2023-11-15 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_auto_20231115_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.project'),
        ),
    ]
