# Generated by Django 3.2.19 on 2023-11-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0027_sprint_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
