# Generated by Django 3.2.19 on 2023-11-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0028_auto_20231117_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slack_channel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
