# Generated by Django 3.2.19 on 2023-11-21 22:47

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0030_employee_slack_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
    ]
